services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./src:/src
      - ./tests:/tests

  worker:
    build:
      context: .
      dockerfile: ./src/worker/Dockerfile
    env_file:
      - ./.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
